FROM fasrc/corona-sunstone-base:5.4
MAINTAINER "Harvard University FAS Research Computing" <rchelp@fas.harvard.edu>

LABEL Description="OneNoVNC image for CORONA"

COPY novnc.sh /usr/local/corona/bin/novnc.sh

CMD ["/usr/local/corona/bin/novnc.sh"]
